"""results.json (run_validation.py) -> tables_C1C2.tex, table_B4.tex (\\input by report.tex)."""
import json

import numpy as np

R = json.load(open('results.json'))
EST = {'legacy/uniform': 'legacy', 'moment/uniform': 'moment, uniform', 'moment/guth': 'moment, Guth'}


def fmt_lam(x):
    return '--' if x is None else ('0' if x == 0 else f'{x:.0e}'.replace('e-0', 'e-').replace('e+0', 'e'))


def c_table(rows, case, refs):
    out = [r'\begin{tabular}{@{}rrl' + 'rrr' * len(refs) + r'@{}}\toprule',
           r'$\sigma$ & $n$ & estimator & ' + ' & '.join(
               rf'\multicolumn{{3}}{{c}}{{vs {ref}}}' for ref in refs.values()) + r'\\',
           ' & & & ' + ' & '.join([r'$\lambda{=}0$ & oracle ($\lambda$) & selected ($\lambda$)'] * len(refs)) + r'\\\midrule']
    keys = sorted({(r['sigma'], r['n'], r['estimator']) for r in rows if r['case'] == case},
                  key=lambda k: (-k[0], k[1], list(EST).index(k[2])))
    for sig, n, est in keys:
        cells = [f'{sig:g}', f'{n}', EST[est]]
        for ref in refs:
            r = next(x for x in rows if x['case'] == case and x['sigma'] == sig and x['n'] == n
                     and x['estimator'] == est and x['ref'] == ref)
            cells += [f"{r['err_lam0']:.4f}", f"{r['err_oracle']:.4f} ({fmt_lam(r['lam_oracle'])})",
                      f"{r['err_selected']:.4f} ({fmt_lam(r['lam_selected'])})"]
        out.append(' & '.join(cells) + r'\\')
    out.append(r'\bottomrule\end{tabular}')
    return '\n'.join(out)


with open('tables_C1C2.tex', 'w') as f:
    f.write('% generated by make_tables.py from results.json\n')
    f.write(r'\begin{table}[h]\centering\scriptsize' + '\n')
    f.write(c_table(R['C1'], 'C1', {'theta_t': r'$\theta_t$', 'theta_ME': r'$\theta^{\rm ME}$'}))
    f.write('\n' + r'\caption{C1, bimodal. Relative error $\|\Theta-\vartheta\|_{G}/\|\vartheta\|_G$ '
            r'(Fisher metric of $p^\sigma_t$, $0.05\le t\le0.95$, MGD sign) against MGD\'s $\theta_t$ '
            r'and against $\theta^{\rm ME}(m_t)$. $\lambda{=}0$ is the per-step $\hat\theta$. '
            r'Oracle: best $\lambda$ of the grid; selected: \code{lam\_path} (held-out loss + veto). '
            r'$n_t=2000$, one seed.}\label{tab:C1}' + '\n' + r'\end{table}' + '\n\n')
    f.write(r'\begin{table}[h]\centering\scriptsize' + '\n')
    f.write(c_table(R['C2'], 'C2', {'exact': r'$\theta_t=\theta^{\rm ME}$'}))
    f.write('\n' + r'\caption{C2, Gaussian ($\phi=x^2$): all projections coincide, '
            r'$\theta_t=\theta^{\rm ME}=1/(2v_t)$. Same conventions as Table~\ref{tab:C1}.}\label{tab:C2}'
            + '\n' + r'\end{table}' + '\n')

with open('table_B4.tex', 'w') as f:
    f.write('% generated by make_tables.py from results.json\n')
    f.write(r'\begin{tabular}{@{}lrrrll@{}}\toprule' + '\n')
    f.write(r'case & $\sigma$ & $n$ & $n_t$ & $\E[z^2]$ per component & lag-1 autocorr.\\\midrule' + '\n')
    for r in R['B4']:
        f.write(f"{r['case']} & {r['sigma']:g} & {r['n']} & {r['nt']} & "
                f"{', '.join(f'{v:.2f}' for v in r['Ez2'])} & {', '.join(f'{v:+.3f}' for v in r['lag1'])}" + r'\\' + '\n')
    f.write(r'\bottomrule\end{tabular}' + '\n')
print('wrote tables_C1C2.tex, table_B4.tex')
